### ISSUE TITLE
Add whitelist request with CDC for ph.state.al.us port 22

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-devops#109]
Please fill out the change request form to allow outbound SSH to "ph.state.al.us" Port 22 in both staging and production. You can test with your -SU account that it's working by opening an SSH session to the Function App containers and then connecting (if you get the login prompt it's working at the firewall level).

**Comment by oslynn** [comment]
@jeremy-page Somehow, it doesn't allow me to Label or tag.

**Comment by jeremy-page** [comment]
Supriya is doing this work, for some reason I can't assign the ticket to her.

**Comment by supriyaaddagada** [comment]
@jeremy-page -  @oslynn  has confirmed that he is able ssh into "ph.state.al.us" Port 22 in both staging and production
