### ISSUE TITLE
Whitelist SFTP servers in staging

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-devops#123]
As we start migrating receivers to the Universal Pipeline we need to have their SFTP servers whitelisted in staging in order for us test.

A list of all SFTP servers that need whitelisting can be found here:
https://cdc.sharepoint.com/:x:/r/teams/ReportStream/_layouts/15/Doc.aspx?sourcedoc=%7B943e946f-d2fc-49f6-8822-5e0a81fb307e%7D&action=edit&activeCell=%27Sheet1%27!D13&wdinitialsession=7fdf7509-99fd-e96b-f528-b3748daffbd8&wdrldsc=10&wdrldc=1&wdrldr=AccessTokenExpiredWarningGatekeeperCookieMismatch%2C

**Comment by jeremy-page** [comment]
This should be done in the next 24 hours. CR # is CHG0035547
