### ISSUE TITLE
Need additional SFTP servers whitelisted

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-devops#125]
There are five  SFTP servers that didn't get whitelisted on this ticket https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/123

Three of them needed to be whitelisted on different ports and the port should now be listed on the sheet here:
https://app.zenhub.com/workspaces/prime-devops-606cb208a8c112000fd48349/issues/gh/cdcgov/prime-devops/123

Two of them are actually on port 22, but didn't get whitelisted.

**Comment by dkrylovsb** [comment]
CHG0036131 submitted.

**Comment by dkrylovsb** [comment]
@victor-chaparro Just as a FYI, I am unable to open a SFTP connection to _oh-doh_ `x.x.28.72` from my workstation on any of the 22, 8222, 4022, or 2022 ports, which likely means that either the server information is incorrect or oh-doh is down or they have a firewall of their own. 

```
bash-3.2$ sftp -P 4022 x.x.28.72
ssh: connect to host x.x.28.72 port 4022: Operation timed out
```

**Comment by dkrylovsb** [comment]
CDC is reporting a FWCR is now in place 
![image](https://github.com/CDCgov/prime-devops/assets/11096575/918f0fc4-ff7f-449f-bf0e-91b39ad4c1bb)

**Comment by dkrylovsb** [comment]
The 3 SFTP servers with non-standard port numbers did not get whitelisted.

**Comment by dkrylovsb** [comment]
Another ticket submitted to CDC 
![image](https://github.com/CDCgov/prime-devops/assets/11096575/10216f08-4ffd-4047-add4-094f5b6757e1)

**Comment by dkrylovsb** [comment]
CDC is reporting this has been implemented 
![image](https://github.com/CDCgov/prime-devops/assets/11096575/9b39cf8b-578a-463d-b2fb-81e7643af291)
