### ISSUE TITLE
Firewall request for ELIMS REST API

### ISSUE THREAD

**Issue by victor-chaparro** [CDCgov/prime-devops#126]
Engagement needs to onboard CDC ELIMS' REST API as receiver. 

We're unable to reach the API in Azure and probably need a firewall request to call the API from Azure.

ELIMS' REST API: https://wshub.elims.development.cdc.gov/HL7/NewMessage

**Comment by supriyaaddagada** [comment]
Created the request CHG0036383 with CDC, will provide an update based on updates from CDC team
