### ISSUE TITLE
ReportStream can not resolve the DNS (domain name: api.neometrics.com)

### ISSUE THREAD

**Issue by oslynn** [CDCgov/prime-devops#129]
ReportStream can not resolve the DNS domain: api.neometrics.com as URLs below:
 "https://api.neometrics.com/natusAPI/api/v2/HL7",
 "https://api.neometrics.com/natusAPI/api/v2/AUTH/Login",
 "https://api.neometrics.com/natusAPI/api/v2/HL7/GetFileEncryptionKey"

Below is the error message:

<img width="871" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBOHNBQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--d577a422541bc5d01ae2fa45f3d47484de2253ea/image.png" alt="image.png" />

Would you please assign someone to look into this?   Thank you very much for your help.

**Comment by dkrylovsb** [comment]
Hi @oslynn from where are these errors originate? Stage, Prod?

**Comment by dkrylovsb** [comment]
@oslynn Appears to be an issue with the CDC DNS server; I will submit a ticket and keep you posted.

**Comment by dkrylovsb** [comment]
RITM0307067 submitted with CDC.

**Comment by dkrylovsb** [comment]
The problem has been fixed by CDC.
