### ISSUE TITLE
CSP Header Issue

### ISSUE THREAD

**Issue by penny-lischer** [CDCgov/prime-devops#131]
Currently in production there are script errors being thrown due to not loading properly.

## Steps to reproduce
1. Go to https://reportstream.cdc.gov/
2. Open dev console
3. Scream

<img width="1270" src="https://api.zenhub.com/attachedFiles/eyJfcmFpbHMiOnsibWVzc2FnZSI6IkJBaHBBN3NKQlE9PSIsImV4cCI6bnVsbCwicHVyIjoiYmxvYl9pZCJ9fQ==--22a162951e664f79d64600450d03e8fafeeb8faa/Screenshot%202024-05-23%20at%2010.26.35%20AM.png" alt="Screenshot 2024-05-23 at 10.26.35 AM.png" />

Suggestions from Joseph:
- Update the CSP headers to allow Azure App Insights weird URL js.monitor.azure
- 
Relates to #[14518](https://app.zenhub.com/workspaces/web-experience-607d9d5e68b95200150fec37/issues/gh/cdcgov/prime-reportstream/14518)

**Comment by dkrylovsb** [comment]
Fixed.
