### ISSUE TITLE
Software Engineer Access for David Holiday

### ISSUE THREAD

**Issue by david-navapbc** [CDCgov/prime-devops#137]
Description
I received my CDC credentials this week and need access to a few things:

Specific Requested resources

- [ ] Super User

- [ ] Azure Access

- [ ]  VPN access for staging/prod

My CDC user id is ZHW5

**Comment by jeremy-page** [comment]
Request sent for the super user account & Azure access. We are not creating VPN profiles for now pending CDC approval.
