### ISSUE TITLE
Deployment build is failing on the Build Router action

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-devops#56]
Two tests are failing, we do not think anything in the code base has changed to cause these failures.
Error 1
`Test test processFunction when ActionLogs has an error() FAILED`
`java.lang.AssertionError: Verification failed: call 1 of 1: WorkflowEngine(#467).isDuplicateItem(any())) was not called`
Error 2
`Test test processFunction duplicate override true to false() FAILED`
 `java.lang.AssertionError: Verification failed: call 1 of 1: ReportFunction(#608).doDuplicateDetection$prime_router(any(), any())) was not called.`  
  `Calls to same mock:`
  `1) ReportFunction(#608).processRequest$prime_router(gov.cdc.prime.router.azure.MockHttpRequestMessage@2d3aa5e5, gov.cdc.prime.router.CovidSender@5944991a)`
  `2) ReportFunction(#608).validateRequest$prime_router(gov.cdc.prime.router.azure.MockHttpRequestMessage@2d3aa5e5)`

**Comment by jeremy-page** [comment]
TODO: Add cron job to build (and test) master daily & alert in slack if it fails

**Comment by jeremy-page** [comment]
We've recreated this with the previous `deploy` branch so we know it is happening when there are no code changes. I have opened an issue on the [Github support site](https://github.community/t/unit-tests-are-failing-now-but-no-code-changes/250481)

**Comment by JosiahSiegel** [comment]
Issue moved to [CDCgov/prime-reportstream #5484](https://github.com/CDCgov/prime-reportstream/issues/5484) via [**ZenHub**](https://www.zenhub.com/)
