### ISSUE TITLE
Configure Sonarcloud to ingest backend reports

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-devops#57]
Currently Sonarcloud is only reading the frontend test results. This means backend code changes show 0% coverage which causes the builds to fail. 

Frontend coverage configuration https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/run_sonarcloud_scan.yaml#L35

**Comment by lucasdze** [comment]
@jeremy-page 
This link  https://github.com/CDCgov/prime-reportstream/blob/master/.github/workflows/run_sonarcloud_scan.yaml#L35 is not working

**Comment by jeremy-page** [comment]
https://github.com/CDCgov/trusted-intermediary/pull/126/files
