### ISSUE TITLE
Update Akamai to support demo environment

### ISSUE THREAD

**Issue by jeremy-page** [CDCgov/prime-devops#61]
Update Akamai with changes to support demo ReportStream environment

**Comment by JosiahSiegel** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:w="urn:schemas-microsoft-com:office:word"
xmlns:m="http://schemas.microsoft.com/office/2004/12/omml"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Word.Document>
<meta name=Generator content="Microsoft Word 15">
<meta name=Originator content="Microsoft Word 15">
<link rel=File-List
href="file:///C:/Users/JOSIAH~1.SIE/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

<link rel=themeData
href="file:///C:/Users/JOSIAH~1.SIE/AppData/Local/Temp/msohtmlclip1/01/clip_themedata.thmx">
<link rel=colorSchemeMapping
href="file:///C:/Users/JOSIAH~1.SIE/AppData/Local/Temp/msohtmlclip1/01/clip_colorschememapping.xml">

<style>

</style>

</head>

<body lang=EN-US link=blue vlink="#954F72" style='tab-interval:.5in;word-wrap:
break-word'>


<div style='mso-element:para-border-div;border:none;border-top:solid #E1E1E1 1.0pt;
padding:3.0pt 0in 0in 0in'>

<p class=MsoNormal style='border:none;mso-border-top-alt:solid #E1E1E1 1.0pt;
padding:0in;mso-padding-alt:3.0pt 0in 0in 0in'><a name="_olk_replyheader"><b>From:
</b></a><a href="mailto:tey1@cdc.gov"><span style='mso-bookmark:_olk_replyheader'>Siegel,
Josiah (CDC/OCOO/OCIO/DSO)</span><span style='mso-bookmark:_olk_replyheader'></span></a><span
style='mso-bookmark:_olk_replyheader'><br>
<b>Sent: </b>Wednesday, September 28, 2022 8:38 AM<br>
<b>To: </b></span><a href="mailto:qks3@cdc.gov"><span style='mso-bookmark:_olk_replyheader'>Blackburn,
Jason (CDC/OCOO/OCIO/CSPO)</span><span style='mso-bookmark:_olk_replyheader'></span></a><span
style='mso-bookmark:_olk_replyheader'>; </span><a href="mailto:lpv1@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>Williams, Rion (CDC/OCOO/OCIO/DSO)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:tex6@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>Page, Jeremy (CDC/OCOO/OCIO/OD)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:htb2@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>Boone, Barbara A. (CDC/OCOO/OCIO/DSO)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'><br>
<b>Cc: </b></span><a href="mailto:tfo3@cdc.gov"><span style='mso-bookmark:_olk_replyheader'>Nesman,
Stephen (CDC/OCOO/OCIO/OD)</span><span style='mso-bookmark:_olk_replyheader'></span></a><span
style='mso-bookmark:_olk_replyheader'>; </span><a href="mailto:ISBhelp@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>DSO ISB Operations Support (CDC)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:oxo1@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>Phan, Hung (CDC/OCOO/OCIO/DSO) (CTR)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:wqd2@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>Theophile, George (CDC/OCOO/OCIO/DSO) (CTR)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:adhelpdsk@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>CDC Active Directory Helpdesk</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:weaknessmanagement@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>CDC OCOO-CSPO Weakness Management</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'>; </span><a href="mailto:kct2@cdc.gov"><span
style='mso-bookmark:_olk_replyheader'>Tisdale, Kenneth (CDC/OCOO/OCIO/DSO)</span><span
style='mso-bookmark:_olk_replyheader'></span></a><span style='mso-bookmark:
_olk_replyheader'><br>
<b>Subject: </b>RE: DNS Changes: Certificate updates for Prime<o:p></o:p></span></p>

</div>

<p class=MsoNormal><span style='mso-bookmark:_olk_replyheader'><span
style='mso-ascii-font-family:Calibri;mso-hansi-font-family:Calibri;mso-bidi-font-family:
Calibri'><o:p>&nbsp;</o:p></span></span></p>

<span style='mso-bookmark:_olk_replyheader'></span>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'>Good morning,<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'>The HSTS update is complete <o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'><br>
(<o:p></o:p></span></p>



Number: | INC0049175
-- | --
Status | Resolved



<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri;color:black'>)</span><span
style='mso-ascii-font-family:Calibri;mso-hansi-font-family:Calibri;mso-bidi-font-family:
Calibri'><o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'>Please proceed with the original request
when possible:<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'><o:p>&nbsp;</o:p></span></p>

<p class=xxmsonormal style='margin-left:.25in'>Last week I received
certificates (original request below this email) with the following updates:<o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l3 level1 lfo1;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>1.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>CN=prime.cdc.gov<o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:1.25in;text-indent:-.25in;
mso-list:l0 level2 lfo2;tab-stops:list 1.0in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>a.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>Add
“Subject Alternative Names”: <br>
demo1.prime.cdc.gov, demo2.prime.cdc.gov, demo3.prime.cdc.gov<o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l1 level1 lfo3;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>2.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>CN=reportstream.cdc.gov<o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:1.25in;text-indent:-.25in;
mso-list:l5 level2 lfo4;tab-stops:list 1.0in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>a.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>Add
“Subject Alternative Names”: <br>
demo1.reportstream.cdc.gov, demo2.reportstream.cdc.gov,
demo3.reportstream.cdc.gov<o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:1.25in'>&nbsp;<o:p></o:p></p>

<p class=xxmsonormal style='margin-left:.25in'><span style='background:yellow;
mso-highlight:yellow'>To proceed, we need the following alias records:</span><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l4 level1 lfo5;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>a.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>alias
(CN) record that redirects <b>demo1.prime.cdc.gov</b> to <b>prime-data-hub-demo1.azurefd.net</b><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l4 level1 lfo5;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>b.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>alias
(CN) record that redirects <b>demo2.prime.cdc.gov</b> to <b>prime-data-hub-demo2.azurefd.net</b><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l4 level1 lfo5;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>c.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>alias
(CN) record that redirects <b>demo3.prime.cdc.gov</b> to <b>prime-data-hub-demo3.azurefd.net</b><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l4 level1 lfo5;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>d.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>alias
(CN) record that redirects <b>demo1.reportstream.cdc.gov</b> to <b>prime-data-hub-demo1.azurefd.net</b><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l4 level1 lfo5;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>e.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>alias
(CN) record that redirects <b>demo2.reportstream.cdc.gov</b> to <b>prime-data-hub-demo1.azurefd.net</b><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l4 level1 lfo5;tab-stops:list .5in'><![if !supportLists]><span
style='mso-fareast-font-family:Calibri'><span style='mso-list:Ignore'>f.<span
style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; </span></span></span><![endif]>alias
(CN) record that redirects <b>demo3.reportstream.cdc.gov</b> to <b>prime-data-hub-demo1.azurefd.net</b><o:p></o:p></p>

<p class=xxmsonormal style='margin-left:.25in'>&nbsp;<o:p></o:p></p>

<p class=xxmsonormal style='margin-left:.25in'>To provide context, the errors
we are receiving are:<o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l2 level1 lfo6;tab-stops:list .5in'><![if !supportLists]><span
style='font-size:10.0pt;mso-bidi-font-size:11.0pt;font-family:Symbol;
mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>We couldn't find a DNS record for custom domain
demo1.<b>prime</b>.cdc.gov that points to Front Door
prime-data-hub-demo1.azurefd.net.<u>To map a domain to this Front Door, create
a CNAME record with your DNS provider for custom domain that points to Front
Door.</u><o:p></o:p></p>

<p class=xxmsolistparagraph style='margin-left:.75in;text-indent:-.25in;
mso-list:l2 level1 lfo6;tab-stops:list .5in'><![if !supportLists]><span
style='font-size:10.0pt;mso-bidi-font-size:11.0pt;font-family:Symbol;
mso-fareast-font-family:Symbol;mso-bidi-font-family:Symbol'><span
style='mso-list:Ignore'>·<span style='font:7.0pt "Times New Roman"'>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
</span></span></span><![endif]>We couldn't find a DNS record for custom domain
demo1.<b>reportstream</b>.cdc.gov that points to Front Door
prime-data-hub-demo1.azurefd.net.<u>To map a domain to this Front Door, create
a CNAME record with your DNS provider for custom domain that points to Front
Door.</u><o:p></o:p></p>

<p class=xxmsonormal>&nbsp;<o:p></o:p></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'><o:p>&nbsp;</o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'>Thanks,<o:p></o:p></span></p>

<p class=MsoNormal><span style='mso-ascii-font-family:Calibri;mso-hansi-font-family:
Calibri;mso-bidi-font-family:Calibri'>Josiah<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>


</body>

</html>
