### ISSUE TITLE
Deploy to Demo Environment notification 

### ISSUE THREAD

**Issue by aurora-a-k-a-lightning** [CDCgov/prime-devops#70]
When a demo environment is deployed to, we would like to see a notification of which demo environment was deployed to including the branch name that was deployed in either the `#prime-reportstream-web-eng` channel or the `#prime-devops` channel - whichever channel is deemed appropriate :smile:

**Comment by jeremy-page** [comment]
Look into Dibs on Stuff plugin so we can "lock" environments (know who's using them)
