### ISSUE TITLE
Integrate Microsoft Defender for Endpoint Cloud Apps (Portal & Terraform)

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-devops#92]
Integrate Microsoft Defender for Endpoint with Microsoft Defender for Cloud Apps

https://learn.microsoft.com/en-us/defender-cloud-apps/mde-integration

**Comment by dkrylovsb** [comment]
@jeremy-page Closing this one as it does not seem to be relevant to PRIME RS
