### ISSUE TITLE
Configure Microsoft Defender on DNS (Portal & Terraform)

### ISSUE THREAD

**Issue by lucasdze** [CDCgov/prime-devops#99]
Microsoft Defender for DNS

https://learn.microsoft.com/en-us/azure/defender-for-cloud/defender-for-dns-introduction

**Comment by dkrylovsb** [comment]
@jeremy-page Our VNets delegate to CDC DNS servers within peered networks, while Defender for DNS only works with Azure DNS. Not applicable to us.
